- name: Add settings to group
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Pre-requisites for mounting iso
      ansible.builtin.assert:
        that:
          - hpegl_auth_token is defined and hpegl_auth_token != ''
          - hpegl_group_id is defined and hpegl_group_id != ''
          - hpegl_os_setting_uri is defined and hpegl_os_setting_uri != ''

    # Compute Ops Group
    - name: Patch with new OS image
      ansible.builtin.uri:
        url: "{{ hpegl_com_region_url }}/compute-ops-mgmt/v1/groups/{{ hpegl_group_id }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ hpegl_auth_token }}"
          Content-Type: application/merge-patch+json
        body:
          name: "{{ hpegl_group }}"
          settingsUris:
            - "{{ hpegl_os_setting_uri }}"
        body_format: json
        return_content: true
        status_code: 200
      retries: "{{ hpegl_uri_retry | default(3) }}"
      delay: "{{ hpegl_uri_delay | default(10) }}"
      register: rg_patch_group_settings
      until: rg_patch_group_settings.status == 200

    - name: Output of patch operation
      ansible.builtin.debug:
        msg: "{{ rg_patch_group_settings }}"
      when: enable_debug is defined and enable_debug

    - name: Wait to sync Compute Ops operations
      ansible.builtin.pause:
        seconds: "{{ wait_for_com_sync | default(5) }}"
