- name: Run OS job
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Pre-requisites for mounting iso
      ansible.builtin.assert:
        that:
          - hpegl_auth_token is defined and hpegl_auth_token != ''
          - hpegl_group_id is defined and hpegl_group_id != ''
          - hpegl_server_ids is defined and hpegl_server_ids|length > 0

    # Compute Ops - Update group image
    # TODO: Create OS settings if not present in group
    #
    # Template Id is hardcoded for COM deployment
    # https://developer.greenlake.hpe.com/docs/greenlake/services/compute-ops-mgmt/public/openapi/compute-ops-mgmt-latest/operation/create_v1_job/
    - name: Prepare body for launching jobs
      ansible.builtin.set_fact:
        run_job_body: |
          {
            "jobTemplate": "e2952628-2629-4088-93db-91742304ef0c",
            "resourceType": "compute-ops/group",
            "resourceId": "{{ hpegl_group_id }}",
            "jobParams": {
              "devices": {{ hpegl_server_ids }},
              "parallel": "{{ parallel_os_install | default(true) }}",
              "stopOnFailure": "{{ stop_on_failure | default(false) }}",
              "osCompletionTimeoutMin": {{ wait_mins_for_os | default(60) | int }}
          }

    # Launch OS installation
    - name: Initiate OS deployment on servers in group
      ansible.builtin.uri:
        url: "{{ hpegl_com_region_url }}/compute-ops-mgmt/v1/jobs"
        method: POST
        headers:
          Authorization: "Bearer {{ hpegl_auth_token }}"
        body: "{{ run_job_body }}"
        body_format: json
        return_content: true
        status_code: [200, 201, 202]
      register: rg_os_install_list

    - name: Print the status of OS installation
      ansible.builtin.debug:
        msg: "{{ rg_os_install_list }}"
